#cloud-config

hostname: roger-luvs-me
fqdn: roger-luvs-me.roger.local

users:
  - name: centos
    ssh-authorized-keys:
      - ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDSct/XRi9HcprTKrvC7YfGiGaJfpLI3W
        59AJNG3nUBAGKbPg5JRQv6Giygdic6/cPWkK6Z98+CUlKvOB0b/d57vNpCbxnyGUvA5WNP
        aBhdHqY2VX12jzqzlsCHiPRa0xqWORSWtqfg15xRUukGYJ5XIfVEQtDKLt/mrHkdWB2mQQ
        == rogerchao@RChaoDUR-MBP.hsd1.ca.comcast.net
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

write_files:

  - path: /etc/sysconfig/network-scripts/ifcfg-eth0
    content: |
        DEVICE=eth0
        BOOTPROTO="none"
        NETMASK="255.255.255.0"
        IPADDR="10.0.0.88"
        GATEWAY="10.0.0.1"
        ONBOOT="yes"

  - path: /etc/resolv.conf
    content: |
        search roger.local
        nameserver 10.0.0.251
        
runcmd:
  - service network restart
