#cloud-config

hostname: roger-luvs-me
fqdn: roger-luvs-me.roger.local

users:
  - name: centos
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv/Ia4YE/NANg3o24QbrFpfp0OAYnlex4ZNq/Du4dhgWZ08lLkOq1GlqWyr2MY/ENrZiiyafixceu7Ox8bDPYM3FONGRc4nchGpkWv3ux/4vWDXq7MiPP0nkhSepK0S4YkFRxd6Gwb6U8vreJK0thiWAjv03VBBE+w9/v3BanzNQe2f8rdiQTKzcw4Xt1ltCD5RJdX//1On4KgrVY5sENWCBdroFIPB1maUjpRB5+C4OHy/a+H9Cg79jv2j26YRoPNglh5mJbda6ivVe/RziIAcuNWc/UnWtzt5ffwDQgCiKGYwcjd4T1TLSqEmzIKNetycAXHP0vFKsXwgAOjXY2n rogerchao@RChaoDUR-MBP.local
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

write_files:

  - path: /etc/sysconfig/network-scripts/ifcfg-eth0
    content: |
        DEVICE=eth0
        BOOTPROTO="none"
        NETMASK="255.255.255.0"
        IPADDR="10.0.0.88"
        GATEWAY="10.0.0.1"
        ONBOOT="yes"

  - path: /etc/resolv.conf
    content: |
        search roger.local
        nameserver 10.0.0.251
        
runcmd:
  - service network restart
